companies/urls.py
# -*- coding: utf-8 -*-
__author__ = 'gollum23'
__date__ = '31/05/14'
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'companies.views',
    url(r'^$', 'home_view', name='home'),
    url(r'^add/$', 'add_view', name='add'),
    url(r'^detalle/(?P<company>[-\w]+)/$', 'detail_view', name='detail'),
    url(r'^editar/(?P<company>[-\w]+)/$', 'edit_view', name='edit'),
)

core/urls.py
# -*- coding: utf-8 -*-
__author__ = 'gollum23'
__date__ = '5/30/14'
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'core.views',
    url(r'^$', 'home_view', name='home'),
    url(r'^logout/$', 'logout_view', name='logout'),
)

iesweb/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^', include('core.urls', namespace='app')),
    url(r'^companias/', include('companies.urls', namespace='companies')),
    url(r'^productos/', include('products.urls', namespace='products')),
    url(r'^clientes/', include('clients.urls', namespace='clients')),
    url(r'^prospectos/', include('prospects.urls', namespace='prospects')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor.urls')),
)

companies/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models
from django.utils.encoding import python_2_unicode_compatible

from helpers.slughifi import slughifi

from core.models import UserTimeStampsModel


@python_2_unicode_compatible
class Company(UserTimeStampsModel):
    name = models.CharField(
        max_length=100,
        verbose_name='Compañia'
    )
    slug = models.SlugField(
        max_length=100,
        verbose_name='Slug',
        blank=True
    )
    nit = models.BigIntegerField(
        verbose_name='Nit'
    )
    digit_verification = models.IntegerField(
        max_length=1,
        verbose_name='',
        blank=True
    )
    address = models.CharField(
        max_length=255,
        verbose_name='Dirección'
    )
    cel_phone = models.BigIntegerField(
        max_length=10,
        verbose_name='Teléfono Celular'
    )
    name_compliance = models.CharField(
        max_length=100,
        verbose_name='Analista Cumplimiento',
        blank=True,
        null=True,
    )
    phone_compliance = models.BigIntegerField(
        max_length=10,
        verbose_name='Teléfono Cumplimiento',
        blank=True,
        null=True
    )
    mail_compliance = models.EmailField(
        max_length=100,
        verbose_name='Email Cumplimiento',
        blank=True,
        null=True
    )
    name_live = models.CharField(
        max_length=100,
        verbose_name='Analista Vida',
        blank=True,
        null=True
    )
    phone_live = models.BigIntegerField(
        max_length=10,
        verbose_name='Teléfono Vida',
        blank=True,
        null=True
    )
    mail_live = models.EmailField(
        max_length=100,
        verbose_name='Email Vida',
        blank=True,
        null=True
    )
    name_car = models.CharField(
        max_length=100,
        verbose_name='Analista Automoviles',
        blank=True,
        null=True
    )
    phone_car = models.BigIntegerField(
        max_length=10,
        verbose_name='Teléfono Automoviles',
        blank=True,
        null=True
    )
    mail_car = models.EmailField(
        max_length=100,
        verbose_name='Email Automoviles',
        blank=True,
        null=True
    )
    name_generals = models.CharField(
        max_length=100,
        verbose_name='Analista Generales',
        blank=True,
        null=True
    )
    phone_generals = models.BigIntegerField(
        max_length=10,
        verbose_name='Teléfono Generales',
        blank=True,
        null=True
    )
    mail_generals = models.EmailField(
        max_length=100,
        verbose_name='Email Generales',
        blank=True,
        null=True
    )

    def __str__(self):
        return '%s' % self.name

    def save(self, *args, **kwargs):
        self.slug = slughifi(self.name)
        super(Company, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Compañia'
        verbose_name_plural = ' Compañias'

core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from django.utils.encoding import python_2_unicode_compatible

from ckeditor.fields import RichTextField
from helpers.slughifi import slughifi
from helpers.dictionaries import PAY_METHOD


class UserTimeStampsModel(models.Model):
    """
    Clase abstracta para el manejo de usuario y  fechas de creación y actualización de registros
    """
    date_create = models.DateTimeField(
        auto_now_add=True
    )
    date_update = models.DateTimeField(
        auto_now=True
    )
    user = models.ForeignKey(
        User,
        related_name="%(app_label)s_%(class)s_ownership"
    )

    class Meta:
        abstract = True


class TimeStampsModel(models.Model):
    """
    Clase abstracta para el manejo de fechas de creación y actualización de registros
    """
    date_create = models.DateTimeField(
        auto_now_add=True
    )
    date_update = models.DateTimeField(
        auto_now=True
    )

    class Meta:
        abstract = True


@python_2_unicode_compatible
class Module(TimeStampsModel):
    """
    Definición de modulos, descripción, url e icono
    """
    name = models.CharField(
        max_length=50,
        verbose_name='Nombre Modulo'
    )
    slug = models.SlugField(
        max_length=50,
        verbose_name=' Slug',
        blank=True
    )
    url = models.CharField(
        max_length=50,
        verbose_name='URL'
    )
    icon = models.CharField(
        max_length=20,
        verbose_name='Icono'
    )
    description = RichTextField(
        verbose_name='Descripción'
    )

    def __str__(self):
        return '%s' % self.name

    def save(self, *args, **kwargs):
        self.slug = slughifi(self.name)
        super(Module, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Módulo'
        verbose_name_plural = 'Módulos'


@python_2_unicode_compatible
class IeswebClient(UserTimeStampsModel):
    """
    Administración de clientes, vigencia de suscripción
    """
    client = models.OneToOneField(
        User,
        related_name='client',
        verbose_name='Cliente'
    )
    paid_until = models.DateField(
        verbose_name='Pagado hasta'
    )
    modules = models.ManyToManyField(
        Module,
        verbose_name='Modulos'
    )
    phone = models.BigIntegerField(
        verbose_name='Teléfono'
    )
    cellphone = models.BigIntegerField(
        verbose_name='Celular'
    )
    mail = models.EmailField(
        verbose_name='Correo electrónico'
    )
    address = models.CharField(
        verbose_name='Dirección',
        max_length='254'
    )

    def __str__(self):
        return '%s' % self.client.get_full_name()

    class Meta:
        verbose_name = 'Usuario'
        verbose_name_plural = 'Usuarios'


@python_2_unicode_compatible
class PaymentHistory(TimeStampsModel):
    """
    Historial de pagos realizados por los clientes
    """
    client = models.ForeignKey(
        IeswebClient,
        verbose_name='Cliente'
    )
    payment_date = models.DateField(
        verbose_name='Fecha de Pago'
    )
    payment_method = models.CharField(
        max_length=50,
        verbose_name='Medio de Pago',
        choices=PAY_METHOD
    )
    payment_amount = models.BigIntegerField(
        verbose_name='Valor pagado'
    )

    def __str__(self):
        return '%s' % self.client.user.get_full_name()

    class Meta:
        verbose_name = 'Historial de pago'
        verbose_name_plural = 'Historial de pagos'

companies/forms.py
# -*- coding: utf-8 -*-
__author__ = 'gollum23'
__date__ = '31/05/14'
from django import forms

from parsley.decorators import parsleyfy

from .models import Company


@parsleyfy
class CompanyForm(forms.ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': 'Compañia'}
        )
    )
    nit = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': 'NIT'}
        )
    )
    digit_verification = forms.IntegerField(
        widget=forms.TextInput(
            attrs={
                'placeholder': '',
                'max': 9,
                'min': 0
            }
        )
    )
    address = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': 'Dirección'}
        )
    )
    cel_phone = forms.IntegerField(
        widget=forms.TextInput(
            attrs={'placeholder': 'Teléfono Celular'}
        )
    )
    name_compliance = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={
                'placeholder': 'Analista Cumplimiento',}
        )
    )
    phone_compliance = forms.IntegerField(
        required=False,
        widget=forms.TextInput(
            attrs={'placeholder': 'Teléfono Cumplimiento'}
        )
    )
    mail_compliance = forms.EmailField(
        required=False,
        widget=forms.TextInput(
            attrs={'placeholder': 'Email Cumplimiento'}
        )
    )
    name_live = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={'placeholder': 'Analista Vida'}
        )
    )
    phone_live = forms.IntegerField(
        required=False,
        widget=forms.TextInput(
            attrs={'placeholder': 'Teléfono Vida'}
        )
    )
    mail_live = forms.EmailField(
        required=False,
        widget=forms.TextInput(
            attrs={'placeholder': 'Email Vida'}
        )
    )
    name_car = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={'placeholder': 'Analista Automoviles'}
        )
    )
    phone_car = forms.IntegerField(
        required=False,
        widget=forms.TextInput(
            attrs={'placeholder': 'Teléfono Automoviles'}
        )
    )
    mail_car = forms.EmailField(
        required=False,
        widget=forms.TextInput(
            attrs={'placeholder': 'Email Automoviles'}
        )
    )
    name_generals = forms.CharField(
        required=False,
        widget=forms.TextInput(
            attrs={'placeholder': 'Analista Generales'}
        )
    )
    phone_generals = forms.IntegerField(
        required=False,
        widget=forms.TextInput(
            attrs={'placeholder': 'Teléfono Generales'}
        )
    )
    mail_generals = forms.EmailField(
        required=False,
        widget=forms.TextInput(
            attrs={'placeholder': 'Email Generales'}
        )
    )

    class Meta:
        model = Company

companies/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.shortcuts import render, redirect

from .forms import CompanyForm
from .models import Company


@login_required(login_url='/')
def home_view(request):
    list_companies = Company.objects.filter(user_id=request.user.id)
    ctx = {
        'list_companies': list_companies
    }
    return render(request, 'companies/home.html', ctx)


@login_required(login_url='/')
def add_view(request):
    form = CompanyForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect(reverse('companies:home'))
    ctx = {
        'form': form
    }
    return render(request, 'companies/add.html', ctx)


@login_required(login_url='/')
def detail_view(request, company):
    company = Company.objects.get(user_id=request.user.id, slug=company)
    ctx = {
        'company': company
    }
    return render(request, 'companies/detail.html', ctx)


@login_required(login_url='/')
def edit_view(request, company):
    company = Company.objects.get(user_id=request.user.id, slug=company)
    form = CompanyForm(request.POST or None, instance=company)
    if form.is_valid():
        form.save()
        return redirect(reverse('companies:home'))
    ctx = {
        'form': form
    }
    return render(request, 'companies/add.html', ctx)

templates/companies/add.html
{% extends 'base_loged.html' %}
{% load static from staticfiles %}
{% block ExtraCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static 'bower_components/parsleyjs/src/parsley.css' %}"/>
{% endblock %}
{% block principal %}
    <section id="wrapper">
        <a href="{% url 'companies:home' %}" class="link-back"><i class="icon-arrow-left"></i> Volver al listado de empresas</a>
        <hr/>
        <section id="company-form">
            <h2>Ingresar Compañia de Seguros</h2>
            <form action="." method="post" data-parsley-validate >
                {% csrf_token %}
                <input name="user" id="id_user" value="{{ user.id }}" type="hidden"/>
                {{ form.name }}
                <div class="left-column-form">{{ form.nit }}</div> <div class="right-column-form">- {{ form.digit_verification }}</div>
                {{ form.address }}
                {{ form.cel_phone }}
                <hr>
                <h3>Analista de Cumplimiento</h3>
                {{ form.name_compliance }}
                {{ form.phone_compliance }}
                {{ form.mail_compliance }}
                <hr>
                <h3>Analista de Vida</h3>
                {{ form.name_live }}
                {{ form.phone_live }}
                {{ form.mail_live }}
                <hr>
                <h3>Analista de Automoviles</h3>
                {{ form.name_car }}
                {{ form.phone_car }}
                {{ form.mail_car }}
                <hr>
                <h3>Analista de Generales</h3>
                {{ form.name_generals }}
                {{ form.phone_generals }}
                {{ form.mail_generals }}
                <hr>
                <div class="action-buttons">
                    <button type="submit" class="btn btn-primary"><i class="icon-disk"></i> Guardar</button>
                </div>
            </form>
        </section>
    </section>
{% endblock %}
{% block ExtraJS %}
    {{ block.super }}
{#    <script src="{% static "bower_components/parsleyjs/src/i18n/es.js" %}"></script>#}
    <script src="{% static "bower_components/parsleyjs/dist/parsley.js" %}"></script>
    <script src="{% static "bower_components/parsleyjs/dist/parsley.remote.js" %}"></script>
{% endblock %}

templates/companies/detail.html
{% extends 'base_loged.html' %}

{% block principal %}
    <section id="wrapper">
        <a href="{% url 'companies:home' %}" class="link-back"><i class="icon-arrow-left"></i> Volver al listado de empresas</a>
        <hr/>
        <section id="detail">
            <p><span>Compañia: </span>{{ company.name }}</p>
            <p><span>Nit: </span>{{ company.nit }} - {{ company.digit_verification }}</p>
            <p><span>Dirección: </span>{{ company.address }}</p>
            <p><span>Teléfono: </span>{{ company.cel_phone }}</p>
            <hr>
            <h3>Analista de Cumplimento</h3>
            <p><span>Analista: </span>{{ company.name_compliance }}</p>
            <p><span>Teléfono: </span>{{ company.phone_compliance }}</p>
            <p><span>Email: </span>{{ company.mail_compliance }}</p>
            <hr>
            <h3>Analista de Vida</h3>
            <p><span>Analista: </span>{{ company.name_live }}</p>
            <p><span>Teléfono: </span>{{ company.phone_live }}</p>
            <p><span>Email: </span>{{ company.mail_live }}</p>
            <hr>
            <h3>Analista de Automoviles</h3>
            <p><span>Analista: </span>{{ company.name_car }}</p>
            <p><span>Teléfono: </span>{{ company.phone_car }}</p>
            <p><span>Email: </span>{{ company.mail_car }}</p>
            <hr>
            <h3>Analista de Generales</h3>
            <p><span>Analista: </span>{{ company.name_generals }}</p>
            <p><span>Teléfono: </span>{{ company.phone_generals }}</p>
            <p><span>Email: </span>{{ company.mail_generals }}</p>
            <hr>
        </section>
    </section>
{% endblock %}

templates/companies/home.html
{% extends 'base_loged.html' %}
{% block principal %}
    <section id="wrapper">
        <h2 class="title-50">Listado de Compañias</h2>
        <div class="action-buttons">
            <a href="{% url 'companies:add' %}" class="btn btn-primary">
                <i class="icon-plus-circle"></i> Agregar Compañia
            </a>
        </div>
        <hr/>
        <section id="tabular-data">
            {% for c in list_companies %}
                <article class="company">
                    <div class="data">
                        <p><span>Compañia: </span>{{ c.name }}</p>
                        <p><span>Nit: </span>{{ c.nit }} - {{ c.digit_verification }}</p>
                        <p><span>Dirección: </span>{{ c.address }}</p>
                        <p><span>Celular: </span>{{ c.cel_phone }}</p>
                    </div>
                    <div class="btn-left"><a href="{% url 'companies:detail' c.slug %}"><i class="icon-profile"></i> Detalle</a></div>
                    <div class="btn-right"><a href="{% url 'companies:edit' c.slug %}"><i class="icon-pencil"></i> Editar</a></div>
                </article>
            {% endfor %}
        </section>
    </section>
{% endblock %}