clients/urls.py
# -*- coding: utf-8 -*-
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'clients.views',
    url(r'^$', 'home_client_view', name='home'),
    # url(r'^(?P<search>.*)$', 'home_filtered_client_view', name='home_filtered_clients'),
    url(r'^add/$', 'add_client_view', name='add'),
    url(r'^detalle/(?P<client>[^/]+)/$', 'detail_client_view', name='detail'),
    url(r'^editar/(?P<client>[^/]+)/$', 'edit_client_view', name='edit'),

    #Peticiones Ajax#
    url(r'^get-tracing/$', 'get_tracing', name='get_tracing_ajax'),
    url(r'^add-tracing/$', 'add_tracing', name='add_tracing_ajax'),
    url(r'^get-products-contracted/$', 'get_products_contracted', name='get_policies_ajax'),
    url(r'^add-product-contracted/$', 'add_product_contracted', name='add_product_contracted_ajax'),
)

core/urls.py
# -*- coding: utf-8 -*-
__author__ = 'gollum23'
__date__ = '5/30/14'
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'core.views',
    url(r'^$', 'home_view', name='home'),
    url(r'^logout/$', 'logout_view', name='logout'),
)

iesweb/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^', include('core.urls', namespace='app')),
    url(r'^companias/', include('companies.urls', namespace='companies')),
    url(r'^productos/', include('products.urls', namespace='products')),
    url(r'^clientes/', include('clients.urls', namespace='clients')),
    url(r'^prospectos/', include('prospects.urls', namespace='prospects')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor.urls')),
)

core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from django.utils.encoding import python_2_unicode_compatible

from ckeditor.fields import RichTextField
from helpers.slughifi import slughifi
from helpers.dictionaries import PAY_METHOD


class UserTimeStampsModel(models.Model):
    """
    Clase abstracta para el manejo de usuario y  fechas de creación y actualización de registros
    """
    date_create = models.DateTimeField(
        auto_now_add=True
    )
    date_update = models.DateTimeField(
        auto_now=True
    )
    user = models.ForeignKey(
        User,
        related_name="%(app_label)s_%(class)s_ownership"
    )

    class Meta:
        abstract = True


class TimeStampsModel(models.Model):
    """
    Clase abstracta para el manejo de fechas de creación y actualización de registros
    """
    date_create = models.DateTimeField(
        auto_now_add=True
    )
    date_update = models.DateTimeField(
        auto_now=True
    )

    class Meta:
        abstract = True


@python_2_unicode_compatible
class Module(TimeStampsModel):
    """
    Definición de modulos, descripción, url e icono
    """
    name = models.CharField(
        max_length=50,
        verbose_name='Nombre Modulo'
    )
    slug = models.SlugField(
        max_length=50,
        verbose_name=' Slug',
        blank=True
    )
    url = models.CharField(
        max_length=50,
        verbose_name='URL'
    )
    icon = models.CharField(
        max_length=20,
        verbose_name='Icono'
    )
    description = RichTextField(
        verbose_name='Descripción'
    )

    def __str__(self):
        return '%s' % self.name

    def save(self, *args, **kwargs):
        self.slug = slughifi(self.name)
        super(Module, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Módulo'
        verbose_name_plural = 'Módulos'


@python_2_unicode_compatible
class IeswebClient(UserTimeStampsModel):
    """
    Administración de clientes, vigencia de suscripción
    """
    client = models.OneToOneField(
        User,
        related_name='client',
        verbose_name='Cliente'
    )
    paid_until = models.DateField(
        verbose_name='Pagado hasta'
    )
    modules = models.ManyToManyField(
        Module,
        verbose_name='Modulos'
    )
    phone = models.BigIntegerField(
        verbose_name='Teléfono'
    )
    cellphone = models.BigIntegerField(
        verbose_name='Celular'
    )
    mail = models.EmailField(
        verbose_name='Correo electrónico'
    )
    address = models.CharField(
        verbose_name='Dirección',
        max_length='254'
    )

    def __str__(self):
        return '%s' % self.client.get_full_name()

    class Meta:
        verbose_name = 'Usuario'
        verbose_name_plural = 'Usuarios'


@python_2_unicode_compatible
class PaymentHistory(TimeStampsModel):
    """
    Historial de pagos realizados por los clientes
    """
    client = models.ForeignKey(
        IeswebClient,
        verbose_name='Cliente'
    )
    payment_date = models.DateField(
        verbose_name='Fecha de Pago'
    )
    payment_method = models.CharField(
        max_length=50,
        verbose_name='Medio de Pago',
        choices=PAY_METHOD
    )
    payment_amount = models.BigIntegerField(
        verbose_name='Valor pagado'
    )

    def __str__(self):
        return '%s' % self.client.user.get_full_name()

    class Meta:
        verbose_name = 'Historial de pago'
        verbose_name_plural = 'Historial de pagos'

core/forms.py
# -*- coding: utf-8 -*-
__author__ = 'gollum23'
__date__ = '5/30/14'
from django import forms
from django.contrib.auth.forms import AuthenticationForm


class MyAuthenticationForm(AuthenticationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': 'Usuario'}
        )
    )
    password = forms.CharField(
        widget=forms.PasswordInput(
            attrs={'placeholder': 'Contraseña'}
        )
    )

core/views.py
# -*- coding: utf-8 -*-
from datetime import date, timedelta
# from django.contrib import messages
from django.contrib.auth import login, logout
from django.db.models import Count
from django.shortcuts import redirect
from django.shortcuts import render
from django.utils import timezone

from .forms import MyAuthenticationForm
from .models import IeswebClient

from clients.models import Tracing, ProductContracted
from companies.models import Company
from products.models import Product


def home_view(request):
    if request.user.is_authenticated():
        ies_client = IeswebClient.objects.get(client=request.user)
        now = timezone.now()  # Get current day with timezone
        after = now + timedelta(days=30)  # set limit to search + 30 days
        before = now - timedelta(days=30)  # set limit to search - 30 days
        # Validate if suscription no expires
        if ies_client.paid_until > date.today():
            list_tracing = Tracing.objects.filter(user=request.user).order_by('-date_create')[:5]
            list_module = ies_client.modules
            list_expiries = ProductContracted.objects.filter(
                date_finish__range=(now, after)
            )
            count_for_companies_latest = ProductContracted.objects.values('product__company__name')\
                .annotate(numero=Count('product'))\
                .filter(date_expedition__range=(before, now))
            count_for_products_latest = ProductContracted.objects.values('product__name')\
                .annotate(numero=Count('product'))\
                .filter(date_expedition__range=(before, now))
            if Company.objects.all():
                company_setup = True
            else:
                company_setup = False
            if Product.objects.all():
                product_setup = True
            else:
                product_setup = False
            ctx = {
                'list_module': list_module,
                'list_tracing': list_tracing,
                'list_expiries': list_expiries,
                'count_for_companies_latest': count_for_companies_latest,
                'count_for_products_latest': count_for_products_latest,
                'company_setup': company_setup,
                'product_setup': product_setup
            }
            return render(request, 'core/index.html', ctx)
        else:
            return render(request, 'core/expired.html')
    else:
        form = MyAuthenticationForm(request, request.POST or None)
        messages = ''
        if form.is_valid():
            if form.get_user() is not None:
                login(request, form.get_user())
                return redirect(request.path)
        ctx = {
            'form': form,
            'message': messages
        }
        return render(request, 'core/login.html', ctx)


def logout_view(request):
    logout(request)
    return redirect('/')

templates/core/expired.html
{% extends 'base_loged.html' %}
{% block sidebar %}

{% endblock %}
{% block principal %}
    <section id="wrapper">
        <h2 class="account_expired text-center">Su suscrupción a terminado, por favor pongase en contacto con el administrador</h2>
        <p class="text-center">ms@mantistecnologia.co</p>
    </section>
{% endblock %}

templates/core/index.html
{% extends 'base_loged.html' %}
{% block principal %}
    <section id="wrapper">

        <div class="action-buttons full-width">
            <a href="{% url 'clients:add' %}" class="btn btn-primary">
                <i class="icon-plus-circle"></i> Agregar Cliente
            </a>
            <a href="{% url 'prospects:add' %}" class="btn btn-primary">
                <i class="icon-plus-circle"></i> Agregar Prospecto
            </a>
            <a href="{% url 'companies:add' %}" class="btn btn-primary">
                <i class="icon-plus-circle"></i> Agregar Compañia
            </a>
            <a href="{% url 'products:home' %}" class="btn btn-primary">
                <i class="icon-plus-circle"></i> Agregar Productos
            </a>
        </div>
        <hr/>
        <div class="alerts">
            {% if not company_setup %}
                <div data-alert class="alert-box warning">
                    Debe configurar la(s) compañia(s) aseguradora(s) <a href="{% url 'companies:add' %}">aquí</a>
                </div>
            {% endif %}
            {% if not product_setup %}
                <div data-alert class="alert-box warning">
                    Debe configurar al menos un producto <a href="{% url 'products:home' %}">aquí</a>
                </div>
            {% endif %}

        </div>
        <section>
            <section id="last-visit" class="widgets-home">
                <h4>Últimas visitas o seguimientos</h4>
                <div class="data">
                    <table>
                        <thead>
                        <tr>
                            <th>Cliente / Prospecto</th>
                            <th>Fecha</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for i in list_tracing %}
                            <tr>
                                <td>{{ i.client.name }}</td>
                                <td>{{ i.date_create }}</td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="2">
                                    No hay seguimientos
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </section>
            <section id="next-expiries" class="widgets-home">
                <h4>Próximos vencimientos</h4>
                <div class="data">
                    <table>
                        <thead>
                        <tr>
                            <th>Cliente</th>
                            <th>Póliza</th>
                            <th>Fecha</th>
                            <th>Compañia</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for p in list_expiries %}
                            <tr>
                                <td>{{ p.client.name }}</td>
                                <td>{{ p.policy_number }} - {{ p.policy_annex }}</td>
                                <td>{{ p.date_finish }}</td>
                                <td>{{ p.product.company.name }}</td>
                            </tr>
                        {% empty %}
                            <tr>
                                <td colspan="4">
                                    No hay vencimientos en los proximos 30 días
                                </td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </section>
            <section id="policies-for-companies" class="widgets-home">
                <h5>Pólizas expedidas por compañia (últimos 30 días)</h5>
                <div class="data">
                    <table>
                        <thead>
                        <tr>
                            <th>Compañia</th>
                            <th>Número</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for c in count_for_companies_latest %}
                            <tr>
                                <td>{{ c.product__company__name }}</td>
                                <td>{{ c.numero }}</td>
                            </tr>
                        {% endfor %}
                        </tbody>
                    </table>
                </div>
            </section>
            <section id="policies-for-products" class="widgets-home">
                <h5>Pólizas expedidas por producto (últimos 30 días)</h5>
                    <div class="data">
                        <table>
                            <thead>
                            <tr>
                                <th>Producto</th>
                                <th>Número</th>
                            </tr>
                            </thead>
                            <tbody>
                                {% for p in count_for_products_latest %}
                                    <tr>
                                        <td>{{ p.product__name }}</td>
                                        <td>{{ p.numero }}</td>
                                    </tr>
                                {% endfor %}
                            </tbody>
                        </table>
                    </div>
            </section>
        </section>
    </section>
{% endblock %}

templates/core/login.html
{% extends 'base.html' %}
{% load static from staticfiles %}
{% block title %}Inteligencia En Seguros{% endblock %}
{% block header %}
    <header>
        <h1>Inteligencia en Seguros</h1>
        <div id="logo_big">
            <img src="{% static "images/logo.svg" %}" alt="Inteligencia En Seguros"/>
        </div>
    </header>
{% endblock %}
{% block principal %}
    {% if form.non_field_errors %}
        <div data-alert class="width-50 alert-box warning radius">
            {% for error in form.non_field_errors %}
                <span>{{ error }}</span>
            {% endfor %}
        </div>
    {% endif %}
    <div id="login-form">
        <h2>Inteligencia en Seguros</h2>
        <form action="." method="post">
            {% csrf_token %}
            {{ form.username.errors }}{{ form.username }}
            {{ form.password.errors }}{{ form.password }}
            <button type="submit" class="btn btn-warning">
                <i class="icon-enter"></i> Ingresar
            </button>
        </form>
        <div class="clearfix"></div>
    </div>
{% endblock %}