core/urls.py
# -*- coding: utf-8 -*-
__author__ = 'gollum23'
__date__ = '5/30/14'
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'core.views',
    url(r'^$', 'home_view', name='home'),
    url(r'^logout/$', 'logout_view', name='logout'),
)

iesweb/urls.py
from django.conf.urls import patterns, include, url

from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns(
    '',
    url(r'^', include('core.urls', namespace='app')),
    url(r'^companias/', include('companies.urls', namespace='companies')),
    url(r'^productos/', include('products.urls', namespace='products')),
    url(r'^clientes/', include('clients.urls', namespace='clients')),
    url(r'^prospectos/', include('prospects.urls', namespace='prospects')),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^ckeditor/', include('ckeditor.urls')),
)

prospects/urls.py
# -*- coding: utf-8 -*-
__author__ = 'gollum23'
__date__ = '7/9/14'
from django.conf.urls import patterns, url

urlpatterns = patterns(
    'prospects.views',
    url(r'^$', 'home_prospect_view', name='home'),
    # url(r'^(?P<search>.*)$', 'home_filtered_client_view', name='home_filtered_clients'),
    url(r'^add/$', 'add_prospect_view', name='add'),
    url(r'^detalle/(?P<client>[^/]+)/$', 'detail_prospect_view', name='detail'),
    url(r'^editar/(?P<client>[^/]+)/$', 'edit_prospect_view', name='edit'),

    #Peticiones Ajax#
    url(r'^get-tracing/$', 'get_tracing', name='get_tracing_ajax'),
    url(r'^add-tracing/$', 'add_tracing', name='add_tracing_ajax'),
)

clients/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.db import models

from core.models import UserTimeStampsModel

from ckeditor.fields import RichTextField
from helpers.slughifi import slughifi
from products.models import Product

from helpers.dictionaries import DOCUMENTS_TYPE


class Client(UserTimeStampsModel):
    name = models.CharField(
        max_length=255,
        verbose_name="Nombre"
    )
    slug = models.SlugField(
        max_length=255,
        verbose_name="Slug",
        blank=True
    )
    type_identification = models.CharField(
        max_length=3,
        verbose_name="Tipo de identificación",
        choices=DOCUMENTS_TYPE
    )
    nit = models.BigIntegerField(
        max_length=10,
        verbose_name="Identificación",
        blank=True
    )
    digit_verification = models.IntegerField(
        max_length=1,
        verbose_name='',
        blank=True
    )
    address = models.CharField(
        max_length=255,
        verbose_name="Dirección"
    )
    city = models.CharField(
        max_length=50,
        verbose_name="Ciudad"
    )
    phone = models.BigIntegerField(
        max_length=10,
        verbose_name="Teléfono",
        blank=True
    )
    cellphone = models.BigIntegerField(
        max_length=10,
        verbose_name="Celular",
        blank=True
    )
    email = models.EmailField(
        max_length=255,
        verbose_name="Correo electrónico",
        blank=True
    )
    contact = models.CharField(
        max_length=255,
        verbose_name="Persona de contacto",
        blank=True
    )
    email_contact = models.EmailField(
        max_length=255,
        verbose_name="Correo electrónico",
        blank=True
    )
    born_date = models.DateField(
        verbose_name="Fecha de nacimiento o creación"
    )
    referred = models.CharField(
        max_length=255,
        verbose_name="Referido por",
        blank=True
    )
    state = models.BooleanField(
        verbose_name="Estado",
        default=True
    )
    is_client = models.BooleanField(
        verbose_name="Cliente",
        default=False
    )
    #TODO pensar en opciones para manejar este campo
    products_to_offer = models.ManyToManyField(
        Product,
        verbose_name="Productos a ofrecer",
        blank=True,
        null=True
    )

    def __unicode__(self):
        return u"%s" % self.name

    def save(self, *args, **kwargs):
        self.slug = slughifi(self.name)
        super(Client, self).save(*args, **kwargs)

    class Meta:
        verbose_name = "Cliente"
        verbose_name_plural = "Clientes"


class Tracing(UserTimeStampsModel):
    client = models.ForeignKey(
        Client,
        verbose_name="Cliente",
        related_name="client_tracing"
    )
    observations = RichTextField(
        verbose_name="Observaciones"
    )

    def __unicode__(self):
        return "%s - %s" % (self.client.name, self.date)

    class Meta:
        verbose_name = "Seguimiento"
        verbose_name_plural = "Seguimientos"
        ordering = ['-date_create']


class ProductContracted(UserTimeStampsModel):
    client = models.ForeignKey(
        Client,
        verbose_name="Cliente",
        related_name="client_product_contracted"
    )
    product = models.ForeignKey(
        Product,
        verbose_name="Producto"
    )
    policy_number = models.CharField(
        max_length=50,
        verbose_name="Número de póliza"
    )
    policy_annex = models.CharField(
        max_length=10,
        verbose_name="Número de anexo",
        blank=True
    )
    date_init = models.DateField(
        verbose_name="Fecha de inicio"
    )
    date_finish = models.DateField(
        verbose_name="Fecha de vencimiento"
    )
    vr_insured = models.BigIntegerField(
        max_length=50,
        verbose_name="Valor asegurado",
        blank=True
    )
    vr_payment = models.BigIntegerField(
        max_length=50,
        verbose_name="Valor prima"
    )
    beneficiary = models.CharField(
        max_length=255,
        verbose_name="Beneficiario",
        blank=True
    )
    observation = RichTextField(
        verbose_name="Observaciones"
    )
    date_expedition = models.DateField(
        verbose_name="Fecha de expedición"
    )

    def __unicode__(self):
        return "%s - %s" % (self.client.name, self.product.name)

    class Meta:
        verbose_name = "Producto Contratado"
        verbose_name_plural = "Productos Contratados"

core/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models
from django.utils.encoding import python_2_unicode_compatible

from ckeditor.fields import RichTextField
from helpers.slughifi import slughifi
from helpers.dictionaries import PAY_METHOD


class UserTimeStampsModel(models.Model):
    """
    Clase abstracta para el manejo de usuario y  fechas de creación y actualización de registros
    """
    date_create = models.DateTimeField(
        auto_now_add=True
    )
    date_update = models.DateTimeField(
        auto_now=True
    )
    user = models.ForeignKey(
        User,
        related_name="%(app_label)s_%(class)s_ownership"
    )

    class Meta:
        abstract = True


class TimeStampsModel(models.Model):
    """
    Clase abstracta para el manejo de fechas de creación y actualización de registros
    """
    date_create = models.DateTimeField(
        auto_now_add=True
    )
    date_update = models.DateTimeField(
        auto_now=True
    )

    class Meta:
        abstract = True


@python_2_unicode_compatible
class Module(TimeStampsModel):
    """
    Definición de modulos, descripción, url e icono
    """
    name = models.CharField(
        max_length=50,
        verbose_name='Nombre Modulo'
    )
    slug = models.SlugField(
        max_length=50,
        verbose_name=' Slug',
        blank=True
    )
    url = models.CharField(
        max_length=50,
        verbose_name='URL'
    )
    icon = models.CharField(
        max_length=20,
        verbose_name='Icono'
    )
    description = RichTextField(
        verbose_name='Descripción'
    )

    def __str__(self):
        return '%s' % self.name

    def save(self, *args, **kwargs):
        self.slug = slughifi(self.name)
        super(Module, self).save(*args, **kwargs)

    class Meta:
        verbose_name = 'Módulo'
        verbose_name_plural = 'Módulos'


@python_2_unicode_compatible
class IeswebClient(UserTimeStampsModel):
    """
    Administración de clientes, vigencia de suscripción
    """
    client = models.OneToOneField(
        User,
        related_name='client',
        verbose_name='Cliente'
    )
    paid_until = models.DateField(
        verbose_name='Pagado hasta'
    )
    modules = models.ManyToManyField(
        Module,
        verbose_name='Modulos'
    )
    phone = models.BigIntegerField(
        verbose_name='Teléfono'
    )
    cellphone = models.BigIntegerField(
        verbose_name='Celular'
    )
    mail = models.EmailField(
        verbose_name='Correo electrónico'
    )
    address = models.CharField(
        verbose_name='Dirección',
        max_length='254'
    )

    def __str__(self):
        return '%s' % self.client.get_full_name()

    class Meta:
        verbose_name = 'Usuario'
        verbose_name_plural = 'Usuarios'


@python_2_unicode_compatible
class PaymentHistory(TimeStampsModel):
    """
    Historial de pagos realizados por los clientes
    """
    client = models.ForeignKey(
        IeswebClient,
        verbose_name='Cliente'
    )
    payment_date = models.DateField(
        verbose_name='Fecha de Pago'
    )
    payment_method = models.CharField(
        max_length=50,
        verbose_name='Medio de Pago',
        choices=PAY_METHOD
    )
    payment_amount = models.BigIntegerField(
        verbose_name='Valor pagado'
    )

    def __str__(self):
        return '%s' % self.client.user.get_full_name()

    class Meta:
        verbose_name = 'Historial de pago'
        verbose_name_plural = 'Historial de pagos'

prospects/models.py
from django.db import models

# Create your models here.

prospects/forms.py
# -*- coding: utf-8 -*-
__author__ = 'gollum23'
__date__ = '7/9/14'
from django import forms

from parsley.decorators import parsleyfy

from clients.models import Client, Tracing, ProductContracted
from products.models import Product
from helpers.dictionaries import DOCUMENTS_TYPE, BOOLEAN_CHOICES


@parsleyfy
class ProspectForm(forms.ModelForm):
    name = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': 'Nombre completo o razón social'}
        )
    )
    type_identification = forms.ChoiceField(
        widget=forms.Select(
            attrs={
                'class': 'chosen-select',
                'data-placeholder': 'Seleccione...',
                'placeholder': 'Seleccione...'
            }
        ),
        choices=DOCUMENTS_TYPE
    )
    nit = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': 'Identificación'}
        )
    )
    digit_verification = forms.IntegerField(
        widget=forms.TextInput(
            attrs={
                'placeholder': '',
                'max': 9,
                'min': 0
            }
        ),
        required=False
    )
    address = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': 'Dirección'}
        )
    )
    city = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': 'Ciudad'}
        )
    )
    phone = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': 'Teléfono'}
        )
    )
    cellphone = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': 'Teléfono celular'}
        )
    )
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={'placeholder': 'Correo electrónico'}
        )
    )
    born_date = forms.DateField(
        widget=forms.DateInput(
            attrs={'class': 'date', 'placeholder': 'Fecha de nacimiento / creación'}
        )
    )
    contact = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': 'Persona de contacto'}
        ),
        required=False
    )
    email_contact = forms.EmailField(
        widget=forms.EmailInput(
            attrs={'placeholder': 'Correo electrónico de contacto'}
        ),
        required=False
    )
    referred = forms.CharField(
        widget=forms.TextInput(
            attrs={'placeholder': 'Referido por'}
        ),
        required=False
    )
    state = forms.CharField(
        widget=forms.Select(
            choices=BOOLEAN_CHOICES
        ),
        label='Estado activo (Si/No)',
        initial=True
    )
    is_client = forms.CharField(
        widget=forms.Select(
            choices=BOOLEAN_CHOICES
        ),
        label='Es cliente (Si/no)',
        initial=False
    )

    class Meta:
        model = Client


@parsleyfy
class TracingForm(forms.ModelForm):
    class Meta:
        model = Tracing

prospects/views.py
from __future__ import unicode_literals
import json
from datetime import timedelta
from django.core.serializers.json import DjangoJSONEncoder
from django.core.urlresolvers import reverse
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, Http404
from django.shortcuts import render, redirect
from django.db.models import Q

from clients.models import Client, Tracing, ProductContracted
from .forms import ProspectForm, TracingForm


@login_required(login_url='/')
def home_prospect_view(request):
    list_prospects = Client.objects.filter(state=True, is_client=False, user=request.user)
    ctx = {
        'list_prospects': list_prospects,
    }
    return render(request, 'prospects/home.html', ctx)


@login_required(login_url='/')
def add_prospect_view(request):
    form = ProspectForm(request.POST or None)
    if form.is_valid():
        form.save()
        return redirect(reverse('prospects:home'))
    ctx = {
        'form': form
    }
    return render(request, 'prospects/add_edit.html', ctx)


@login_required(login_url='/')
def detail_prospect_view(request, client):
    prospect = Client.objects.get(nit=client)
    form_tracing = TracingForm()
    # form_product = ProductContractForm()
    ctx = {
        'prospect': prospect,
        'formTracing': form_tracing
        # 'formProduct': form_product
    }
    return render(request, 'prospects/detail.html', ctx)


@login_required(login_url='/')
def edit_prospect_view(request, client):
    prospect = Client.objects.get(nit=client)
    form = ProspectForm(request.POST or None, instance=prospect)
    if form.is_valid():
        form.save()
        return redirect(reverse('prospects:home'))
    ctx = {
        'form': form
    }
    return render(request, 'prospects/add_edit.html', ctx)


###########PETICIONES AJAX##################
@login_required(login_url='/')
def get_tracing(req):
    if req.is_ajax() and req.method == 'POST':
        tracing = Tracing.objects.filter(client__id=req.POST['prospect'])
        list_tracing = []
        for t in tracing:
            date_t = t.date_create - timedelta(hours=5)
            track = {
                'id': t.id,
                'date': date_t,
                'observation': t.observations
            }
            list_tracing.append(track)
        return HttpResponse(
            json.dumps(list_tracing, cls=DjangoJSONEncoder),
            content_type='application/json; chartset=utf8'
        )
    else:
        raise Http404


@login_required(login_url='/')
def add_tracing(request):
    if request.is_ajax() and request.method == 'POST':
        form = TracingForm(request.POST)
        if form.is_valid():
            form.save()
            return HttpResponse(status=200)
    else:
        raise Http404

templates/prospects/add_edit.html
{% extends 'base_loged.html' %}
{% load static from staticfiles %}
{% block ExtraCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static "bower_components/chosen_v1.1.0/chosen.css" %}"/>
    <link rel="stylesheet" href="{% static "bower_components/jquery.ui/dist/jquery-ui.css" %}"/>
{% endblock %}
{% block principal %}
    <section id="wrapper">
        <a href="{% url 'prospects:home' %}" class="link-back"><i class="icon-arrow-left"></i> Volver al listado de prospectos</a>
        <section id="client-form">
            <h2>Ingresar Cliente</h2>
            <form action="." method="post" data-parsley-validate>
                {% csrf_token %}
                <input name="user" id="id_user" value="{{ user.id }}" type="hidden"/>
                {{ form.name }}
                {{ form.type_identification }}
                <div class="left-column-form">{{ form.nit }}</div> <div class="right-column-form">- {{ form.digit_verification }}</div>
                {{ form.address }}
                {{ form.city }}
                <div class="left-column-form">{{ form.phone }}</div>
                <div class="right-column-form">{{ form.cellphone }}</div>
                <div class="left-column-form">{{ form.email }}</div>
                <div class="right-column-form">{{ form.born_date }}</div>
                <hr>
                <h3>Contacto</h3>
                {{ form.contact }}
                {{ form.email_contact }}
                <hr>
                {{ form.referred }}
                <p><label for="id_state">{{ form.state.label }}</label>
                {{ form.state }}</p>
                <p><label for="id_is_client">{{ form.is_client.label }}</label>
                {{ form.is_client }}</p>
                <hr/>
                <div class="action-buttons">
                    <button type="submit" class="btn btn-primary"><i class="icon-disk"></i> Guardar</button>
                </div>
            </form>
        </section>
    </section>
{% endblock %}
{% block ExtraJS %}
    {{ block.super }}
    <script src="{% static "bower_components/parsleyjs/src/i18n/es.js" %}"></script>
    <script src="{% static "bower_components/parsleyjs/dist/parsley.min.js" %}"></script>
{#    <script src="{% static "js/parsley.extend.min.js" %}"></script>#}
    <script src="{% static "bower_components/jquery.ui/dist/jquery-ui.js" %}"></script>
    <script src="{% static "js/client_add.js" %}"></script>
{% endblock %}

templates/prospects/detail.html
{% extends 'base_loged.html' %}
{% load static from staticfiles %}
{% block ExtraCSS %}
    {{ block.super }}
    <link rel="stylesheet" href="{% static "bower_components/chosen_v1.1.0/chosen.css" %}"/>
    <link rel="stylesheet" href="{% static "bower_components/jquery.ui/dist/jquery-ui.css" %}"/>
{% endblock %}
{% block ExtraJSTop %}
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor/ckeditor.js' %}"></script>
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor/config.js' %}"></script>
    <script type="text/javascript" src="{% static 'ckeditor/ckeditor/lang/en.js' %}"></script>
{% endblock %}

{% block principal %}
    <section id="wrapper">
        <a href="{% url 'prospects:home' %}" class="link-back"><i class="icon-arrow-left"></i> Volver al listado de prospectos</a>
        <section id="colleft-client">
            <section id="detail-prospect">
                <h2>{{ prospect.name }}</h2>
                <p><span>Identificación: </span>{{ prospect.nit }} <span>Tipo: </span>{{ prospect.get_type_identification_display }}</p>
                <p><span>Dirección: </span>{{ prospect.address }}</p>
                <p><span>Ciudad: </span>{{ prospect.city }}</p>
                <p><span>Teléfono: </span>{{ prospect.phone }} <span>Celular: </span>{{ prospect.cellphone }}</p>
                <p><span>Email: </span>{{ prospect.email }}</p>
                <p><span class="full-width">Fecha de creación o nacimiento: </span>{{ prospect.born_date }}</p>
                <hr>
                <h3>Contacto</h3>
                <p><span>Contacto: </span>{{ prospect.contact }}</p>
                <p><span>Email: </span>{{ prospect.email_contact }}</p>
                <hr>
                <p><span class="full-width">Referido por: </span>{{ prospect.referred }}</p>
{#                <div class="action-buttons"><a id="switch_views" class="btn btn-primary" href="#"><i class="icon-briefcase"></i> Ver Pólizas</a></div>#}
            </section>
        </section>
        <div class="vertical"></div>
        <section id="colright-client">
            <section id="tracing-client">
                <h2>Seguimiento</h2>
                <div class="action-buttons"><a class="btn btn-primary add-tracing" data-reveal-id="modal-add-tracing" data-client="{{ client.id }}" href="#"><i class="icon-plus-circle"></i> Agregar seguimiento</a></div>
                <hr/>
                <div id="list_tracing_ajax"></div>
            </section>
{#            <section id="products-client">#}
{#                <h2>Pólizas</h2>#}
{#                <div class="action-buttons"><a class="btn btn-primary add-policy" href="#" data-reveal-id="modal-add-product"><i class="icon-plus-circle"></i> Agregar pólizas</a></div>#}
{#                <hr/>#}
{#                <div id="list_products_ajax"></div>#}
{#            </section>#}
        </section>
    </section>
    <section id="modal-add-tracing" class="reveal-modal medium" data-reveal>
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h3>Agregar Seguimiento</h3>
                </div>
                <div class="modal-body">
                    <form id="tracing_form" action="." method="post">
                        {% csrf_token %}
                        <input name="user" id="id_user" value="{{ user.id }}" type="hidden"/>
                        {{ formTracing.observations }}
                        <input type="hidden" id="id_client" name="client" value="{{ prospect.id }}"/>
                        <button class="btn btn-primary btn-right btn-add-tracing"><i class="icon-disk"></i> Guardar</button>
                    </form>
                </div>
                <div class="modal-footer">
                    <button id="close-modal" type="button" class="close-reveal-modal btn btn-primary ">
                        <i class="icon-close"> Cerrar</i>
                </button>
                </div>
            </div>
        </div>
    </section>
{#    <section id="modal-add-product" class="reveal-modal medium" data-reveal>#}
{#        <div class="modal-dialog">#}
{#            <div class="modal-content">#}
{#                <div class="modal-header">#}
{#                    <h3>Agregar Producto</h3>#}
{#                </div>#}
{#                <div class="modal-body">#}
{#                    <form id="product-add-form" action="." method="post">#}
{#                        {% csrf_token %}#}
{#                        <input name="user" id="id_user" value="{{ user.id }}" type="hidden"/>#}
{#                        <input type="hidden" id="id_client" name="client" value="{{ client.id }}"/>#}
{#                        {{ formProduct.product.label_tag }} {{ formProduct.product }}#}
{#                        <div class="left-column-form">#}
{#                            {{ formProduct.policy_number.label_tag }}{{ formProduct.policy_number }}#}
{#                            {{ formProduct.date_init.label_tag }}{{ formProduct.date_init }}#}
{#                            {{ formProduct.vr_insured.label_tag }}{{ formProduct.vr_insured }}#}
{#                        </div>#}
{#                        <div class="right-column-form">#}
{#                            {{ formProduct.policy_annex.label_tag }}{{ formProduct.policy_annex }}#}
{#                            {{ formProduct.date_finish.label_tag }}{{ formProduct.date_finish }}#}
{#                            {{ formProduct.vr_payment.label_tag }}{{ formProduct.vr_payment }}#}
{#                        </div>#}
{#                        <p>{{ formProduct.beneficiary.label }}{{ formProduct.beneficiary }}</p>#}
{#                        <p>Observaciones</p>#}
{#                        {{ formProduct.observation }}#}
{#                        <button type="submit" class="btn btn-primary btn-right btn-add-product"><i class="icon-disk"></i> Guardar</button>#}
{#                    </form>#}
{##}
{#                </div>#}
{#                <div class="modal-footer">#}
{#                    <button id="close-modal" type="button" class="btn btn-primary" data-dismiss="modal">#}
{#                        <i class="icon-cancel-circle"> Cerrar</i>#}
{#                    </button>#}
{#                </div>#}
{#            </div>#}
{#        </div>#}
{#    </section>#}
{% endblock %}
{% block ExtraJS %}
    {{ block.super }}
    <script src="{% static "bower_components/jquery.ui/dist/jquery-ui.js" %}"></script>
    <script src="{% static "bower_components/moment/min/moment.min.js" %}"></script>
    <script src="{% static "bower_components/moment/lang/es.js" %}"></script>
    <script src="{% static "js/prospects.js" %}"></script>
    <script>
        var PROSPECT = {{ prospect.id }};
    </script>
{% endblock %}

templates/prospects/home.html
{% extends 'base_loged.html' %}
{% block principal %}
    <section id="wrapper">
        <h2 class="title-module">Listado de prospectos</h2>
        <div id="search">
{#            <form action=".">#}
{#                <input type="text" id="search-text" name="search" placeholder="Buscar clientes"/>#}
{#                <button type="submit" class="btn btn-primary" id="btn-search"><i class="icon-binoculars"></i> Buscar</button>#}
{#            </form>#}
        </div>
        <div class="action-buttons title-module">
            <a href="{% url 'prospects:add' %}" class="btn btn-primary">
                <i class="icon-plus-circle"></i> Agregar Prospecto
            </a>
        </div>
        <hr/>


        <section id="tabular-data">
            {% for c in list_prospects %}
                <article class="client">
                    <div class="data">
                        <p><span>Nombre: </span><br/>{{ c.name|truncatechars:40 }}</p>
                        <p><span>Identificación: </span>{{ c.nit }}</p>
                        <p><span>Teléfono: </span>{{ c.phone }}</p>
                        <p><span>Correo electrónico: </span><br/>{{ c.email }}</p>
                        <p><span>Último seguimiento: </span>{% for i in c.client_tracing.all %}{% if forloop.first %}{{ i.date_create }}{% endif %}{% empty %}No ha ingresado seguimientos{% endfor %}</p>
                    </div>
                    <div class="btn-left"><a href="{% url 'prospects:detail' c.nit %}"><i class="icon-file6"></i> Detalle</a></div>
                    <div class="btn-right"><a href="{% url 'prospects:edit' c.nit %}"><i class="icon-pencil2"></i> Editar</a></div>
                </article>
            {% endfor %}
        </section>

    </section>
{% endblock %}
{% block ExtraJS %}
    {{ block.super  }}
    <script>
        {# TODO: revisar ajax para busqueda de clientes y prospectos #}
        $(document).ready(init);

        function init(){
            $("#btn-search").on("click", search);
        }
        function search(e){
            e.preventDefault();
            var q = $("#search-text").val();
            $.get('/clientes/'+ q, show_results)
        }
        function show_results(data){
            console.log("Funcion resultado");
            console.log(data);
{#            $("section#tabular-data").html("{% for c in list_clients_ajax %}{% if forloop.first %}<table><thead><tr><td>Nombre</td><td>Nit</td><td>Teléfono</td><td>Correo electrónico</td><td>Último seguimiento</td><td></td><td></td></tr></thead><tbody>{% endif %}<tr><td>{{ c.name }}</td><td>{{ c.nit }}</td><td>{{ c.phone }}</td><td>{{ c.email }}</td><td>{% for i in c.client_tracing.all %}{% if forloop.last %}{{ i.date }}{% endif %}{% endfor %}</td><td><a href='{% url 'detail_company' c.slug %}'>Detalle</a></td><td><a href='{% url 'edit_company' c.slug %}'><i class='icon-pencil2'></i> Editar</a></td></tr>{% if forloop.last %}</tbody></table>{% endif %}{% endfor %}")#}
            $("section#tabular-data").html("<table></table>")
        }
    </script>
{% endblock %}